DEBUG: "0"
DATABASE: "postgres"
SQL_ENGINE: "django.db.backends.postgresql"
SQL_DATABASE: "hairitage"
SQL_USER: "hairst_usr"
CLOUD_SQL_CONNECTION_NAME: "hairitage-studion-web:africa-south1:hairitage-db"
GS_BUCKET_NAME: "hairitage-studion-web-assets"
GCS_PUBLIC_BUCKET: "0"
DJANGO_ALLOWED_HOSTS: "hairitage-studio.co.za,www.hairitage-studio.co.za,.run.app"
COLLECT_STATIC: "1"
EMAIL_HOST: "smtp.gmail.com"
EMAIL_HOST_USER: "info@hairitage-studio.co.za"
EMAIL_PORT: "465"
EMAIL_USE_TLS: "False"
EMAIL_USE_SSL: "True"
DEFAULT_FROM_EMAIL: "info@hairitage-studio.co.za"
DEFAULT_NO_REPLY_EMAIL: "Hairitage Studio <noreply@hairitage-studio.co.za>"
