services:
  web:
    build:
      context: ./app
      dockerfile: Dockerfile
    command: gunicorn hairitage.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./app:/home/app/web
    ports:
      - "8000:8000"
    env_file:
      - ./.env.local
    depends_on:
      - db
    expose:
      - 8000
  db:
    image: postgres:15
    volumes:
        - ./_data:/var/lib/postgresql/data/
    env_file:
      - .env.db.local
  worker:
    build:
      context: ./app
      dockerfile: Dockerfile
    command: sh -c "while true; do python manage.py send_appointment_reminders; sleep 60; done"
    env_file:
      - ./.env.local
    depends_on:
      - db
    restart: unless-stopped

  adminer:
    image: adminer
    restart: always
    environment:
      ANER_DESIGN: pepa-linha #nicu
    depends_on:
      - db
    ports:
      - "7580:8080"
  nginx:
    build: ./nginx
    ports:
      - "1337:80"
    depends_on:
      - web
    volumes:
      - ./app:/home/app/web