# Generated by Django 5.0

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PriceCategory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers appear first.')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Price Category',
                'verbose_name_plural': 'Price Categories',
                'ordering': ('order', 'name'),
            },
        ),
        migrations.CreateModel(
            name='PriceItem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('price_from', models.DecimalField(decimal_places=2, max_digits=8)),
                ('price_to', models.DecimalField(blank=True, decimal_places=2, help_text='Leave blank for a fixed price, or set a higher amount to show a range (e.g. R350 – R550).', max_digits=8, null=True)),
                ('duration_minutes', models.PositiveIntegerField(blank=True, help_text='Approximate duration in minutes, shown next to the price.', null=True)),
                ('note', models.CharField(blank=True, help_text="Optional short note, e.g. 'Long hair may incur an extra charge'.", max_length=150)),
                ('is_popular', models.BooleanField(default=False, help_text='Highlights this item as a popular choice.')),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers appear first within the category.')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='pricing.pricecategory')),
            ],
            options={
                'verbose_name': 'Price Item',
                'verbose_name_plural': 'Price Items',
                'ordering': ('order', 'name'),
            },
        ),
    ]
