# Generated by Django 5.0 on 2023-12-15 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('photo', models.ImageField(upload_to='teams/')),
                ('position', models.CharField(max_length=100, unique=True)),
                ('intro', models.TextField()),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ('name',)},
        ),
    ]
