# Generated by Django 5.0 on 2023-12-15 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0002_team_alter_service_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='team',
            options={'ordering': ('name', 'position', 'created_at')},
        ),
    ]
