# Generated by Django 5.0 on 2023-12-17 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0004_alter_team_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='icon',
            field=models.TextField(),
        ),
    ]
