# Generated by Django 5.2.6 on 2025-09-08 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0006_category_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='updated_at',
            field=models.DateField(auto_now=True),
        ),
    ]
