# Generated by Django 5.2.6 on 2025-09-08 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0007_item_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='featured_image',
            field=models.ImageField(blank=True, null=True, upload_to='category_images/'),
        ),
    ]
