# Generated by Django 5.0 on 2023-12-15 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('rate', models.IntegerField()),
                ('title', models.CharField(max_length=100)),
                ('banner', models.ImageField(upload_to='promotions/')),
                ('description', models.TextField()),
                ('home_page', models.BooleanField(default=False)),
            ],
        ),
    ]
