# Generated by Django 5.0 on 2023-12-16 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20231216_0717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'draft'), ('PUBLISH', 'publish')], default='draft', max_length=100),
        ),
    ]
