# Generated by Django 5.0 on 2023-12-18 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_alter_post_content_alter_post_intro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='type',
            field=models.CharField(choices=[('blog', 'blog'), ('content', 'content')], default='blog', max_length=100),
        ),
    ]
