# Generated by Django 5.0 on 2023-12-18 06:07

from django.db import migrations
from datetime import date


class Migration(migrations.Migration):
    dependencies = [
        ('blog', '0010_category'),
    ]
    current_date = date.today()

    insert_sql = """
        INSERT INTO blog_category(name,created_at) VALUES
            ('Hairstyle', current_date),
            ('Beauty & skin care',current_date),
            ('Nails',current_date),
            ('Make up', current_date)
    """
    reverse_sql = """
     TRUNCATE TABLE blog_category
    """

    operations = [
        migrations.RunSQL(
            sql=insert_sql,
            reverse_sql=reverse_sql
        )
    ]
