# Generated by Django 5.0 on 2023-12-18 06:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('blog', '0011_auto_20231218_0607'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category_id',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='blog.category'),
        ),
    ]
