# Generated by Django 5.0 on 2023-12-16 16:07

from django.db import migrations


class Migration(migrations.Migration):
    insert_sql = """
    INSERT INTO configuration_setting(
    currency_name,
    currency_code,
    physical_address,
    contact_number,
    email_address,
    display_name,
    opening_hours) VALUES
    ('Rand', 'ZAR', '46 Van Riebeck Avenue  Edenvale <br />  Johannesburg 1609','+27 84 393 9484','info@hairitage-studio.co.za','Hairitage Studio', 'Monday - Friday <br /> 08:00am - 09:00pm')
    """

    dependencies = [
        ('configuration', '0002_rename_settings_setting_rename_stats_stat'),
    ]

    operations = [
        migrations.RunSQL(
            sql=insert_sql,
        )
    ]