# Generated by Django 5.0 on 2023-12-18 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0004_alter_setting_contact_intro_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Setting',
            new_name='Settings',
        ),
        migrations.RenameModel(
            old_name='Stat',
            new_name='Stats',
        ),
        migrations.AlterModelOptions(
            name='settings',
            options={'verbose_name_plural': 'settings'},
        ),
        migrations.AlterModelOptions(
            name='stats',
            options={'verbose_name_plural': 'stats'},
        ),
    ]
